# Generated by Django 5.0.2 on 2024-02-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Unknown', max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('author_image', models.ImageField(default='unknown.png', upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('platform', models.CharField(default='LincSoftwares', max_length=100)),
                ('username', models.CharField(default='Lincoln_331', max_length=100)),
            ],
        ),
    ]
